### ISSUE TITLE
Reproduction of DOSCO

### ISSUE THREAD

**Issue by parang99** [KaiyangZhou/CoOp#55]
Hi @KaiyangZhou 
Thanks for sharing your great work. 

I tried to reproduce DOSCO table in the CoOp paper, but I got a little bit different performance compared with table 7.
I followed as you mentioned in README.md to apply DOSCO in CoOp. 

I brought 
- 7 config files [on-device-dg/configs/datasets/p_*.yaml](https://github.com/KaiyangZhou/on-device-dg/tree/main/configs/datasets) for datasets
- 7 dataset python files [on-device-dg/datasets/p_*.py](https://github.com/KaiyangZhou/on-device-dg/tree/main/datasets)
- 1 model architecture config file [rn50_ctxv1.yaml](https://github.com/KaiyangZhou/on-device-dg/blob/main/configs/prompts/CoOp/rn50_ctxv1.yaml)

 Also, there was some code modification in [train.py](https://github.com/KaiyangZhou/CoOp/blob/main/train.py) for running (e.g., `import datasets.p_*` and `cfg.DATASET.ENV = "2k"`).
Lastly, run  [coop.sh](https://github.com/KaiyangZhou/on-device-dg/blob/main/scripts/prompts/coop.sh)

The results are below: 

|ResNet-50|P-Air|P-Cars|P-Ctech|P-Ins|P-Mam|P-Pets|P-UCF|
|--------------|--------------|--------------|--------------|--------------|--------------|--------------|--------------|
|CoOp|22.1|60.7|89.4|66.3|61.6|83.8|60.6|
|Reproduce|21.67 <br> $\pm$ 0.13|62.55 <br> $\pm$ 2.33|89.85 <br> $\pm$ 0.83|64.96 <br> $\pm$ 0.85|61.79 <br> $\pm$ 0.41|85.35 <br> $\pm$ 0.66|70.61 <br> $\pm$ 0.75|

In P-UCF, the score gap is very big(+10). I heard that the scores are not the same because the torch seed is not fixed(even though I mentioned it), but I don't think the score will be 10 points apart. I think I missed something when following DOSCO, but I failed to find out why. 

Q1. Can you let me know if something is wrong or missing?

There is another simple question. 
Q2. Is the each score in table 7 the average of 3 seeds(seed: 1, 2, 3)?
It is confusing because I cannot see the standard deviations. 

Thanks, 
Janet

**Comment by KaiyangZhou** [comment]
The code for reproducing CoOp's results are here https://github.com/KaiyangZhou/on-device-dg.

hi @yuhangzang maybe you can take a look? thx

**Comment by yuhangzang** [comment]
Hi @parang99 

Yes, we use the average results of 3 random seeds. You can check the results for various seeds in this excel spreadsheet: https://docs.google.com/spreadsheets/d/1R8UzQg5NbtVV9L3PGvVNEBYEF9OUgNGg/edit?usp=share_link&ouid=106436633304095692959&rtpof=true&sd=true 

<img width="825" alt="image" src="https://user-images.githubusercontent.com/31362732/217708507-6322bb19-d0ff-4fc9-85fd-d8071876d36d.png">

The CoOp result presented in our paper for P-UCF is 69.2, not 60.6 as you stated. 60.6 is the result for CLIP. It may be due to different random numbers/GPUs, the results you run out will have some differences, but it is far less exaggerated than 10 points.

You may use this code https://github.com/KaiyangZhou/on-device-dg and see if the score difference is still substantial.

**Comment by parang99** [comment]
Very Thanks!!
