### ISSUE TITLE
question about gradients on text encoder

### ISSUE THREAD

**Issue by vincentlux** [KaiyangZhou/CoOp#7]
Hi, may I ask if the gradients of the original CLIP text encoder are frozen or not? The paper mentioned that the gradients of text encoder is frozen, but I couldn't find that part in the code... Thanks a lot for your help!

**Comment by KaiyangZhou** [comment]
It doesn't matter whether the text encoder's gradients are turned off because in the code only the prompt tokens (i.e. `prompt_learner`) are given to the optimizer.

We turned off the gradients in the image encoder to reduce gpu memory consumption. This might be a bit misleading.

We have now changed the code to turn off gradients in both encoders to avoid confusion.

commit: https://github.com/KaiyangZhou/CoOp/commit/be57b16c86f3de7d7135bf51930bf0276cb3b2ac

**Comment by vincentlux** [comment]
Got it, thanks a lot for your quick response!
